	     print "ELIMNA: Il grafo rimane connesso quindi elimina l'arco",acr;
		 let A_En := A_En + 1;
	  	 let A_E[A_En] := acr;
		 let g_rimossi := g_rimossi union {acr};
		 let grafo := grafo diff {acr};
		 let lgrafo := card(grafo);
      	 # ricalcola CT togliendo il costo dell'arco appena tolto
	 	 # ricalcola TT togliendo la trasmissione  dell'arco appena tolto
	  	 let CT := CT - w[acr];
	  	 let TT := TT - c[acr];
