repeat while CT > B {
	   commands dot_grafo.run;
       if (A_Nn == A) then break;
	   let cc := cc + 1;
	   let jj := first(g_non_rimossi);
	   print "BUDGET: Fase di scambio finale: elimino l'arco",jj," (",nod[jj,1],",",nod[jj,2],") w=",w[jj]," c=",c[jj];
	   let g_non_rimossi := g_non_rimossi diff {jj};
	   let grafo := grafo diff {jj};
	   let oldacr := jj;
	   let acr := jj;
	   let s := nod[acr,1];
	   let t := nod[acr,2];
	   commands sostituisci_arco.run;
}
